name = "iai-flow-engine"
main = "workers/api/src/index.ts"
compatibility_date = "2025-03-01"

workers_dev = false

routes = [
  { pattern = "api.flow.iai.one", custom_domain = true }
]

[vars]
APP_NAME = "IAI Flow Engine"

[durable_objects]
bindings = [
  { name = "EXECUTION_COORDINATOR", class_name = "ExecutionCoordinator" }
]

[[migrations]]
tag = "v1"
new_classes = ["ExecutionCoordinator"]
